# Generated by Django 2.2.1 on 2019-06-24 07:37

from django.db import migrations, models
import django.db.models.deletion
import doctor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=doctor.models.content_file_name_submitted)),
                ('report', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorDetails')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.PatientDetails')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Types')),
            ],
        ),
        migrations.CreateModel(
            name='PendingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=doctor.models.content_file_name_pending)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.DoctorDetails')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.PatientDetails')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Types')),
            ],
        ),
    ]
